aws_region = "us-west-2"
azure_resource_group_name = "my-resource-group"
azure_location = "East US"
azure_vnet_address_space = ["10.0.0.0/16"]
azure_cluster_count = 2
azure_node_count = 2
azure_vm_size = "Standard_DS2_v2"
azure_script_url = "https://your-storage-account.blob.core.windows.net/scripts/node_setup.sh"
aws_vpc_cidr = "10.1.0.0/16"
aws_public_subnet_1_cidr = "10.1.1.0/24"
aws_public_subnet_2_cidr = "10.1.2.0/24"
aws_db_username = "admin"
aws_db_password = "your_secure_password_here"
